zpb_admin_sites_homepage:
    path: /
    defaults: { _controller: ZPBAdminBundle:Site:index }
    methods: ["GET"]

zpb_admin_sites_create:
    path: /create
    defaults: { _controller: ZPBAdminBundle:Site:xhrCreateSite }
    methods: ["POST"]

zpb_admin_sites_delete:
    path: /delete
    defaults: { _controller: ZPBAdminBundle:Site:xhrDeleteSite }
    methods: ["DELETE"]

zpb_admin_sites_update:
    path: /update
    defaults: { _controller: ZPBAdminBundle:Site:xhrUpdateSite }
    methods: ["PUT"]






