<?php

namespace ZPB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimalRepository extends EntityRepository
{
    public function getOneWithSpecies($id)
    {
        $qb = $this->createQueryBuilder("a")->join("a.species","s")->addSelect("s");
        $qb->where($qb->expr()->eq("a.id", $id));
        return $qb->getQuery()->getOneOrNullResult();
    }
}
