<?php

namespace ZPB\AdminBundle\Entity;

use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * AnimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimalRepository extends SortableRepository
{
    public function getOneWithSpecies($id)
    {
        $qb = $this->createQueryBuilder("a")
            ->join("a.species","s")->addSelect("s")
            ->leftJoin("a.category", "c")->addSelect("c");
        $qb->where($qb->expr()->eq("a.id", $id));
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getByCategoryId($catId)
    {
        $qb = $this->createQueryBuilder("a")
            ->join("a.category", "c");
        $qb->where($qb->expr()->eq("c.id", $catId));
        return $qb->getQuery()->getResult();
    }
}
