<?php

namespace ZPB\AdminBundle\Entity;


/**
 * DraftPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DraftPostRepository extends PostableRepository
{
}
