<?php

namespace ZPB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DraftPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DraftPostRepository extends EntityRepository
{
    public function getPosts()
    {
        $qb = $this->createQueryBuilder("d")
            ->join("d.post", "p")->addSelect("p");

        return $qb->getQuery()->getResult();
    }
}
