<?php

namespace ZPB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GalleryToSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryToSiteRepository extends EntityRepository
{
    public function getSitesArray($id)
    {
        $qb = $this->createQueryBuilder("s")->select("s.siteShortcut as share")->where("s.galleryId = :id");
        $qb->setParameter("id", $id);
        $result = $qb->getQuery()->getArrayResult();
        return array_map(function($it){ return $it["share"]; }, $result);
    }

    public function findBySite($site)
    {
        $qb = $this->createQueryBuilder("g")->where("g.siteShortcut = :shortname");
        $qb->setParameter("shortname", $site->getShortName());
        return $qb->getQuery()->getResult();
    }

    public function findByGallery($gallery)
    {
        $qb = $this->createQueryBuilder("g")->where("g.galleryId = :id");
        $qb->setParameter("id", $gallery->getId());
        return $qb->getQuery()->getResult();
    }
}
