<?php

namespace ZPB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GalleryToSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryToSiteRepository extends EntityRepository
{
    public function getSitesArray($id)
    {
        $qb = $this->createQueryBuilder("s")->select("s.siteShortcut as share")->where("s.galleryId = :id");
        $qb->setParameter("id", $id);
        $result = $qb->getQuery()->getArrayResult();
        return array_map(function($it){ return $it["share"]; }, $result);
    }
}
