<?php

namespace ZPB\AdminBundle\Entity;

use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * HeaderCarouselSlideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeaderCarouselSlideRepository extends SortableRepository
{
}
