<?php

namespace ZPB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageGalleryRepository extends EntityRepository
{
    public function getSharedGalleries($shortname)
    {
        $q = $this->_em->createQuery("SELECT g FROM ZPBAdminBundle:ImageGallery g WHERE g.id IN (SELECT s.galleryId FROM ZPBAdminBundle:GalleryToSite s WHERE s.siteShortcut = :shortname)");
        $q->setParameter("shortname", $shortname);
        return $q->getArrayResult();
    }
}
