<?php

namespace ZPB\AdminBundle\Entity;


/**
 * PublishPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublishPostRepository extends PostableRepository
{
}
