<?php

namespace ZPB\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantRepository extends EntityRepository
{
    public function findAllToArray()
    {
        $qb = $this->createQueryBuilder("r")->orderBy("r.name", "ASC");
        return $qb->getQuery()->getArrayResult();
    }
}
