<?php

namespace ZPB\AdminBundle\Entity;


/**
 * TrashPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrashPostRepository extends PostableRepository
{
}
