zpb_image_galleries_homepage:
    path: /
    defaults: { _controller: ZPBAdminBundle:ImageGalleries:index }
    methods: ["GET"]

zpb_image_galleries_xhr_create:
    path: /gallery/create
    defaults: { _controller: ZPBAdminBundle:ImageGalleries:xhrNewGallery }
    methods: ["POST"]

zpb_image_galleries_update:
    path: /gallery/{id}
    defaults: { _controller: ZPBAdminBundle:ImageGalleries:update }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_image_galleries_delete:
    path: /gallery/{id}
    defaults: { _controller: ZPBAdminBundle:ImageGalleries:deleteGallery }
    methods: ["DELETE"]
    requirements:
        id: \d+
