zpb_sites_jdb:
    resource: "@ZPBSitesJDBBundle/Resources/config/routing.yml"
    prefix:   /
    host: new.lesjardinsdebeauval.com
    schemes: ["http"]

zpb_sites_sco:
    resource: "@ZPBSitesScoBundle/Resources/config/routing.yml"
    prefix:   /
    host: new.scolaires.zoobeauval.com
    schemes: ["http"]

zpb_sites_pro:
    resource: "@ZPBSitesProBundle/Resources/config/routing.yml"
    prefix:   /
    host: new.pro.zoobeauval.com
    schemes: ["http"]

zpb_sites_ce:
    resource: "@ZPBSitesCEBundle/Resources/config/routing.yml"
    prefix:   /
    host: new.ce.zoobeauval.com
    schemes: ["http"]

zpb_sites_bn:
    resource: "@ZPBSitesBNBundle/Resources/config/routing.yml"
    prefix:   /
    host: new.beauvalnature.com
    schemes: ["http"]

zpb_admin:
    resource: "@ZPBAdminBundle/Resources/config/routing.yml"
    prefix:   /
    host: new.admin.zooparc.com
    schemes: ["http"]

zpb_sites_zoo:
    resource: "@ZPBSitesZooBundle/Resources/config/routing.yml"
    prefix:   /
    host: new.zoobeauval.com
    schemes: ["http"]

zpb_sites_common:
    resource: "@ZPBSitesCommonBundle/Resources/config/routing.yml"
    prefix:   /
