zpb_sites_ce_homepage:
    path:     /
    defaults: { _controller: ZPBSitesCEBundle:Index:index }
    methods: ["GET"]

zpb_sites_ce_contact:
    path:     /contact
    defaults: { _controller: ZPBSitesCEBundle:Contact:index }
    methods: ["GET"]

zpb_sites_ce_faq:
    path:     /questions-frequentes
    defaults: { _controller: ZPBSitesCEBundle:FAQ:index }
    methods: ["GET"]

zpb_sites_ce_legales:
    path: /mentions-legales
    defaults: { _controller: ZPBSitesCEBundle:Miscellaneous:legals }
    methods: ["GET"]

zpb_sites_ce_cgv:
    path: /conditions-generales-de-vente
    defaults: { _controller: ZPBSitesCEBundle:Miscellaneous:cgv }
    methods: ["GET"]

################################# english
zpb_sites_ce_en_routes:
    prefix: /en
    resource: "@ZPBSitesCEBundle/Resources/config/routing/en.yml"


















