zpb_sites_sco_homepage:
    path:     /
    defaults: { _controller: ZPBSitesScoBundle:Index:index }

zpb_sites_sco_contact:
    path:     /contact
    defaults: { _controller: ZPBSitesScoBundle:Contact:index }
