zpb_admin_homepage:
    path:     /
    defaults: { _controller: ZPBAdminBundle:Index:index }
    methods: ["GET"]

_console:
    resource: "@CoreSphereConsoleBundle/Resources/config/routing.yml"
    host: new.admin.zooparc.com
    schemes: ["http"]
    prefix: /_console

zpb_admin_faqs_routes:
    prefix: /faqs
    resource: "@ZPBAdminBundle/Resources/config/routing/faq.yml"

zpb_admin_sites_routes:
    prefix: /sites
    resource: "@ZPBAdminBundle/Resources/config/routing/site.yml"

zpb_admin_pdfs_routes:
    prefix: /pdfs
    resource: "@ZPBAdminBundle/Resources/config/routing/pdfs.yml"

############################################# press

zpb_admin_press_release_routes:
    prefix: /press/communique
    resource: "@ZPBAdminBundle/Resources/config/routing/press/press_release.yml"

zpb_admin_press_kit_routes:
    prefix: /press/dossier
    resource: "@ZPBAdminBundle/Resources/config/routing/press/press_kit.yml"

############################################# documentation
zpb_admin_doc_routes:
    prefix: /documentation
    resource: "@ZPBAdminBundle/Resources/config/routing/doc.yml"

############################################# phototheque
zpb_admin_phototek_routes:
    prefix: /phototheque
    resource: "@ZPBAdminBundle/Resources/config/routing/phototheque/routes.yml"


############################################# image galleries
zpb_admin_image_galleries_routes:
    prefix: /image-galleries
    resource: "@ZPBAdminBundle/Resources/config/routing/image_galleries/routes.yml"

############################################# zoo
zpb_admin_zooparc_staticpage_routes:
    prefix: /zooparc/pages-statiques
    resource: "@ZPBAdminBundle/Resources/config/routing/zooparc/staticpage.yml"

zpb_admin_zooparc_carousel_routes:
    prefix: /zooparc/carousel
    resource: "@ZPBAdminBundle/Resources/config/routing/zooparc/carousel.yml"

zpb_admin_zooparc_restauration_routes:
    prefix: /zooparc/restauration
    resource: "@ZPBAdminBundle/Resources/config/routing/zooparc/restauration.yml"

zpb_admin_zooparc_alerts_routes:
    prefix: /zooparc/alertes
    resource: "@ZPBAdminBundle/Resources/config/routing/zooparc/alerts.yml"

zpb_admin_zooparc_frontbox_routes:
    prefix: /zooparc/frontbox
    resource: "@ZPBAdminBundle/Resources/config/routing/zooparc/frontbox.yml"

############################################# animal
zpb_admin_animal_routes:
    prefix: /animal
    resource: "@ZPBAdminBundle/Resources/config/routing/animal/animal.yml"
zpb_admin_species_routes:
    prefix: /species
    resource: "@ZPBAdminBundle/Resources/config/routing/animal/species.yml"
zpb_admin_animal_category_routes:
    prefix: /animal/category
    resource: "@ZPBAdminBundle/Resources/config/routing/animal/animal_category.yml"


############################################# sponsoring

############################################# post
zpb_admin_post_write:
    path: /posts/ecrire
    defaults: { _controller: ZPBAdminBundle:Post/Post:write }
    methods: ["GET"]

zpb_admin_post_save_draft:
    path: /post/save/draft
    defaults: { _controller: ZPBAdminBundle:Post/Post:xhrSaveDraft }
    methods: ["POST"]

zpb_admin_post_save_publish:
    path: /post/save/publish
    defaults: { _controller: ZPBAdminBundle:Post/Post:xhrSavePublish }
    methods: ["POST"]


zpb_admin_draft_post_routes:
    prefix: /posts/brouillons
    resource: "@ZPBAdminBundle/Resources/config/routing/post/draft.yml"

zpb_admin_published_post_routes:
    prefix: /posts/publies
    resource: "@ZPBAdminBundle/Resources/config/routing/post/published.yml"

zpb_admin_trash_post_routes:
    prefix: /posts/corbeille
    resource: "@ZPBAdminBundle/Resources/config/routing/post/trash.yml"


############################################# bn
zpb_admin_bn_staticpage_routes:
    prefix: /beauvalnature/pages-statiques
    resource: "@ZPBAdminBundle/Resources/config/routing/bn/staticpage.yml"

zpb_admin_bn_carousel_routes:
    prefix: /beauvalnature/carousel
    resource: "@ZPBAdminBundle/Resources/config/routing/bn/carousel.yml"

















