zpb_admin_homepage:
    path:     /
    defaults: { _controller: ZPBAdminBundle:Index:index }
    methods: ["GET"]

zpb_admin_sites_routes:
   prefix: /sites
   resource: "@ZPBAdminBundle/Resources/config/routing/site.yml"

############################################# alertes
zpb_admin_alerts_routes:
    prefix: /alerts
    resource: "@ZPBAdminBundle/Resources/config/routing/alerts.yml"


############################################# image galleries
zpb_admin_image_galleries_routes:
    prefix: /image-galleries
    resource: "@ZPBAdminBundle/Resources/config/routing/image_galleries/routes.yml"

############################################# zoo
zpb_admin_zooparc_staticpage_routes:
    prefix: /zooparc/pages-statiques
    resource: "@ZPBAdminBundle/Resources/config/routing/zooparc/staticpage.yml"

zpb_admin_zooparc_carousel_routes:
    prefix: /zooparc/carousel
    resource: "@ZPBAdminBundle/Resources/config/routing/zooparc/carousel.yml"

zpb_admin_zooparc_restauration_routes:
    prefix: /zooparc/restauration
    resource: "@ZPBAdminBundle/Resources/config/routing/zooparc/restauration.yml"





############################################# bn
zpb_admin_bn_staticpage_routes:
    prefix: /beauvalnature/pages-statiques
    resource: "@ZPBAdminBundle/Resources/config/routing/bn/staticpage.yml"

zpb_admin_bn_carousel_routes:
    prefix: /beauvalnature/carousel
    resource: "@ZPBAdminBundle/Resources/config/routing/bn/carousel.yml"

















