zpb_sites_zoo_news_news:
    path: /{page}
    defaults: { _controller: ZPBSitesZooBundle:News:news, page: 1 }
    methods: ["GET"]
    requirements:
        page: \d+

zpb_sites_zoo_news_single:
    path: /article/{slug}
    defaults: { _controller: ZPBSitesZooBundle:News:newsSingle }
    methods: ["GET"]

zpb_sites_zoo_news_nouveautes:
    path: /nouveautes
    defaults: { _controller: ZPBSitesZooBundle:News:nouveautes }
    methods: ["GET"]








